### ISSUE TITLE
It is impossible to view the runtime log file

### ISSUE THREAD

**Issue by AlekseyZabrodin2** [pableess/Bleess.Extensions.Logging.File#3]
Good afternoon, I have such a problem when I set up logging to write to a file, and I open this file in Visual Studio Code to monitor events, there is no such possibility.
There is no possibility of auto-updating when reading the runtime file.

**Comment by pableess** [comment]
This library simply writes log output to the text file via an open file.  VS Code loads the entire document in memory when you open the file.  IF you want a live view of the file you would need to use a VS Code extensions that will "tail" a file.  Something like, https://marketplace.visualstudio.com/items?itemName=berublan.vscode-log-viewer.

Another option would be to use a shell command like "tail" (linux), or "Get-Content -wait" (powershell) to watch log files in real time.

**Comment by AlekseyZabrodin2** [comment]
But in a logger like NLog, there is such an opportunity to view the runtime, including the autoFlush="true" property

**Comment by pableess** [comment]
I have published a new version with 2 new options which control the behavior of how the file writer will flush to disk

See https://github.com/pableess/Bleess.Extensions.Logging.File/tree/master?tab=readme-ov-file#flush-behavior

I think if you set the following, it will behave how you expect.

  "MaxFlushInterval": 0,  // flush every write
  "FlushToDisk" :  true,  // make flush calls, fsync

**Comment by pableess** [comment]
fixed in #4

**Comment by AlekseyZabrodin2** [comment]
Thank you very much, it helped a lot, we stay in touch)))
